version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
         - image: cimg/base:2022.09
         - image: cimg/node:18.9.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests in headless mode
          command: npm run test
