version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - run:
        name: Xvfb dependency.
        command: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests in headless mode
          command: npm run test
