version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:18.9.1
    steps:
      - checkout
      - run:
          name: Install xvfb dependency.
          command: sudo apt install xvfb
      - run:
          name: Install libnss3 dependency.
          command: sudo apt install libnss3
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests in headless mode
          command: npm run test
