name: Every push in main
on: [push]
jobs:
  warp-e2e-run:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm ci
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
      
