name: Cron to run Cypress e2e 
on: 
  schedule:
    - cron: "*/5 * * * *"
jobs:
  warp-e2e-run:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
      - name: npm install
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

            
            
